### ISSUE TITLE
Screen only display on the top left corner after upgrade to HWC2.0

### ISSUE THREAD

**Issue by txu4** [android-ia/external-drm_hwcomposer#7]

**Comment by txu4** [comment]
In HWC1.x, the modes are listed from the highest to the lowest resolution, like below

Display Devices: size=1
  DisplayDeviceInfo{"Built-in Screen": uniqueId="local:0", 1920 x 1080, modeId 1, defaultModeId 1, supportedModes [{id=1, width=1920, height=1080, fps=60.0}, {id=2, width=1600, height=1200, fps=60.0}, {id=3, width=1600, height=900, fps=60.0}, {id=4, width=1280, height=1024, fps=75.0}, {id=5, width=1280, height=1024, fps=60.0}, {id=6, width=1152, height=864, fps=75.0}, {id=7, width=1024, height=768, fps=75.0}, {id=8, width=1024, height=768, fps=60.0}, {id=9, width=800, height=600, fps=75.0}, {id=10, width=800, height=600, fps=60.0}, {id=11, width=640, height=480, fps=75.0}, {id=12, width=640, height=480, fps=60.0}, {id=13, width=720, height=400, fps=70.0}], colorTransformId 1, defaultColorTransformId 1, supportedColorTransforms [{id=1, colorTransform=0}], HdrCapabilities android.view.Display$HdrCapabilities@17847bf, density 92, 92.015 x 91.44 dpi, appVsyncOff 0, presDeadline 17666667, touch INTERNAL, rotation 0, type BUILT_IN, state ON, FLAG_DEFAULT_DISPLAY, FLAG_ROTATES_WITH_CONTENT, FLAG_SECURE, FLAG_SUPPORTS_PROTECTED_BUFFERS}

While after upgrade to HWC2.0, the sequence is inversed. The HWC always select the first mode. The 720x400 is picked now, instead of 1920x1080

Display Devices: size=1
  DisplayDeviceInfo{"Built-in Screen": uniqueId="local:0", 720 x 400, modeId 1, defaultModeId 1, supportedModes [{id=1, width=720, height=400, fps=70.0}, {id=2, width=640, height=480, fps=60.0}, {id=3, width=640, height=480, fps=75.0}, {id=4, width=800, height=600, fps=60.0}, {id=5, width=800, height=600, fps=75.0}, {id=6, width=1024, height=768, fps=60.0}, {id=7, width=1024, height=768, fps=75.0}, {id=8, width=1152, height=864, fps=75.0}, {id=9, width=1280, height=1024, fps=60.0}, {id=10, width=1280, height=1024, fps=75.0}, {id=11, width=1600, height=900, fps=60.0}, {id=12, width=1600, height=1200, fps=60.0}, {id=13, width=1920, height=1080, fps=60.0}], colorMode 0, supportedColorModes [], HdrCapabilities android.view.Display$HdrCapabilities@a69d6308, density 213, 34.505 x 33.866 dpi, appVsyncOff 0, presDeadline 15285714, touch INTERNAL, rotation 0, type BUILT_IN, state ON, FLAG_DEFAULT_DISPLAY, FLAG_ROTATES_WITH_CONTENT, FLAG_SECURE, FLAG_SUPPORTS_PROTECTED_BUFFERS}

**Comment by tpalli** [comment]
yeah, it should iterate through modes and select one that is DRM_MODE_TYPE_PREFERRED, this should match panel native resolution

**Comment by txu4** [comment]
@tpalli Good suggestion, here is the patch, I will verify it tomorrow

commit 328c72c092e34d32070dbed07519450ea16c7a43
Author: Randy Xu <randy.xu@intel.com>
Date:   Thu Nov 10 22:45:17 2016 +0800

    Choose the mode with DRM_MODE_TYPE_PREFERRED bit as default one

    Solve "Screen only display on the top left corner after upgrade to HWC2.0"
    Issue: https://github.com/android-ia/external-drm_hwcomposer/issues/7

    Signed-off-by: Randy Xu <randy.xu@intel.com>

diff --git a/drmhwctwo.cpp b/drmhwctwo.cpp
index 769d7ba..9e3c3dc 100644
--- a/drmhwctwo.cpp
+++ b/drmhwctwo.cpp
@@ -393,7 +393,9 @@ HWC2::Error DrmHwcTwo::HwcDisplay::GetDisplayConfigs(uint32_t *num_configs,
   for (const DrmMode &mode : connector_->modes()) {
     if (idx >= *num_configs)
       break;
-    configs[idx++] = mode.id();
+    if (mode.type() & DRM_MODE_TYPE_PREFERRED) {
+      configs[idx++] = mode.id();
+    }
   }
   *num_configs = idx;
   return HWC2::Error::None;

**Comment by kalyankondapally** [comment]
Instead of this, lets make sure Preferred is in the top of the list when creating the list of supported modes i.e. DrmConnector::UpdateModes()

**Comment by kalyankondapally** [comment]
Created a pull request for this: https://github.com/android-ia/external-drm_hwcomposer/pull/10

**Comment by kalyankondapally** [comment]
Closing this as above patches seem to have fixed it.

**Comment by txu4** [comment]
@kalyankondapally No, the patch cannot solve the issue, so reopen it.

With the patch, the listed mode is weired

Display Devices: size=1
  DisplayDeviceInfo{"Built-in Screen": uniqueId="local:0", -1 x -1, modeId 1, defaultModeId 1, supportedModes [{id=1, width=-1, height=-1, fps=-1.0E9}, {id=2, width=1920, height=1080, fps=60.0}], colorMode 0, supportedColorModes [], HdrCapabilities android.view.Display$HdrCapabilities@a69d6308, density 213, 213.0 x 213.0 dpi, appVsyncOff 0, presDeadline 999999, touch INTERNAL, rotation 0, type BUILT_IN, state ON, FLAG_DEFAULT_DISPLAY, FLAG_ROTATES_WITH_CONTENT, FLAG_SECURE, FLAG_SUPPORTS_PROTECTED_BUFFERS}

**Comment by kalyankondapally** [comment]
Hmm, is it selecting your prefered mode and using it ?

**Comment by txu4** [comment]
This patch can solve the issue, please review
https://github.com/txu4/external-drm_hwcomposer/commit/0fb9abf9214895d073abdb3a63f15a1af3f3a896 

Ideally, we need sort all  modes per PREFERRED bit and resolution and expose them in HWC2, while in Android usage, only the single preferred mode is required.

**Comment by tpalli** [comment]
It's still failing for me, I'm not sure why .. so what I did is this:
https://github.com/tpalli/external-drm_hwcomposer/commits/sort_modes

I'm still encountering some strange trouble though but I think it might be related to dpi .. not sure. Can you give above branch a try?

**Comment by txu4** [comment]
@tpalli I also tried to sort the drm modes, but I have weird issue, the HWC get the right mode but the display is set wrong (low resolution). 

The patch https://github.com/txu4/external-drm_hwcomposer/commit/0fb9abf9214895d073abdb3a63f15a1af3f3a896 works for me, I will check the mode sort issue more next Monday.

**Comment by kalyankondapally** [comment]
lets split preferred mode selection and low resolution. Few places to look at:
1) HwcDisplay::GetDisplayAttribute we have things like  static const int32_t kUmPerInch = 25400;
  uint32_t mm_width = connector_->mm_width();
uint32_t mm_height = connector_->mm_height();
2)https://github.com/android-ia/device-androidia/commit/a76244a401408358d437ad62ae30483d719f5180  see if this needs to be changed in anyway

**Comment by kalyankondapally** [comment]
Looking into hwc2 code in frameworks, it queries for no of configs first, than requests to populate the configs and than populate all attributes for each config. So, I am not sure any more if sorting helps. For resolution I think we need to look at HwcDisplay::GetDisplayAttribute and see if we need to tweak anything there depending on different scenarios.

**Comment by txu4** [comment]
@tpalli Kalyan has refined the patch and merge to android-ia, do you still see the issue after the new patch set?

**Comment by tpalli** [comment]
yeah now it seems to work ok, I don't quite understand why sorting did not fix it but I'm happy using current approach!

**Comment by kalyankondapally** [comment]
Closing this for now.
